### ISSUE TITLE
Out-of-the-box Broken Installation

### ISSUE THREAD

**Issue by m0pam** [yeswehack/pwn-machine#20]
I've attempted installing multiple times, on both Ubuntu 22 and on Debian 11, on fresh virtual instances image, all updated and upgraded, it always ends up with this error:

```sh
 => => naming to docker.io/library/pwn-machine-traefik                                                                                                                                                        0.0s
 => [pwn-machine-powerdns  3/11] COPY pdns.list /etc/apt/sources.list.d/pdns.list                                                                                                                             0.0s
 => [pwn-machine-powerdns  4/11] COPY pdns /etc/apt/preferences.d/pdns                                                                                                                                        0.1s
 => [pwn-machine-powerdns  5/11] RUN bash -c 'curl https://repo.powerdns.com/CBC8B383-pub.asc | apt-key add -'                                                                                                0.9s
 => [pwn-machine-powerdns  6/11] RUN apt-get update                                                                                                                                                           2.4s
 => ERROR [pwn-machine-powerdns  7/11] RUN apt-get install pdns-server pdns-backend-mysql mariadb-client  -y                                                                                                  2.6s
------
 > [pwn-machine-powerdns  7/11] RUN apt-get install pdns-server pdns-backend-mysql mariadb-client  -y:
#0 0.438 Reading package lists...
#0 1.330 Building dependency tree...
#0 1.509 Reading state information...
#0 1.567 Some packages could not be installed. This may mean that you have
#0 1.567 requested an impossible situation or if you are using the unstable
#0 1.567 distribution that some required packages have not yet been created
#0 1.567 or been moved out of Incoming.
#0 1.567 The following information may help to resolve the situation:
#0 1.567 
#0 1.569 The following packages have unmet dependencies:
#0 1.657  pdns-server : Depends: libboost-program-options1.67.0 but it is not installable
#0 1.657                Depends: libssl1.1 (>= 1.1.1) but it is not installable
#0 1.657                Recommends: pdns-backend-bind but it is not going to be installed
#0 1.660 E: Unable to correct problems, you have held broken packages.
------
failed to solve: executor failed running [/bin/sh -c apt-get install pdns-server pdns-backend-mysql mariadb-client  -y]: exit code: 100
```

Running `apt-get install pdns-server pdns-backend-mysql mariadb-client  -y` myself doesn't return any errors, everything is already installed successfully. Note that this doesn't seem to be a broken dependency issue at all? 

The service pdns is correctly running.

I cannot debug this further, and it seems to be an out-of-the-box issue.

Please may you provide assistance?

**Comment by SakiiR** [comment]
Hey ! 

Yes it's not building, I personnaly use this image for powerdns.
```
FROM ubuntu@sha256:adf73ca014822ad8237623d388cedf4d5346aa72c270c5acc01431cc93e18e2d
```

**Comment by m0pam** [comment]
I've switched to that one and the powerdns problem is gone, so thanks for that @SakiiR, but now it fails because of a **failed yarn build**. This is on a fresh vps (tested with ubu22 and ubu20), so no need to add specific details imo.

Can anyone help?

:(

**Comment by SakiiR** [comment]
ok,

Which container failed to build in the `yarn build` process ? Please, can you provide logs ?

**Comment by m0pam** [comment]
Hey there @SakiiR, I'm attaching the full logs as my words probably wouldn't be of much help.
This machine is a test one (ubuntu 22) so there shouldn't be any sensitive information, but please warn me if you see any.

[logs.txt](https://github.com/yeswehack/pwn-machine/files/9864143/logs.txt)

**Comment by SakiiR** [comment]
Hey,

One of the dependencies should be out of date or incompatible with the current source code.

I will try to investigate more later.

**Comment by m0pam** [comment]
Any updates?

**Comment by BZHunt** [comment]
> I've switched to that one and the powerdns problem is gone, so thanks for that @SakiiR, but now it fails because of a **failed yarn build**. This is on a fresh vps (tested with ubu22 and ubu20), so no need to add specific details imo.
> 
> Can anyone help?
> 
> :(

I am having the same issue as of today on a brand new Ubuntu 22.10 VPS
Any update on this ?

**Comment by SakiiR** [comment]
Hey @BZHunt,

Did you try with the actual master branch ? the whole problem is supposed to be fixed with the following merge request:

[!21](https://github.com/yeswehack/pwn-machine/pull/21)

**Comment by BZHuntShampu** [comment]
Hey @SakiiR 

Sorry I sent the first message using the wrong account.
Yes I did clone the actual master branch that includes the #21 merge.

During the build of `manager`  I get the following JS stacktrace : 

```
Step 7/18 : RUN yarn build
 ---> Running in a5e757d61afa
yarn run v1.22.5
$ quasar build

 Build mode........ spa
 Pkg quasar........ v1.15.19
 Pkg @quasar/app... v2.2.8
 Debugging......... no
 Publishing........ no

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 Configured browser support (at least 87.68% of global marketshare):
 · Chrome for Android >= 90
 · Firefox for Android >= 87
 · Android >= 90
 · Chrome >= 80
 · Edge >= 87
 · Firefox >= 79
 · iOS >= 11.0-11.2
 · Opera >= 71
 · Safari >= 11.1

 App · Running "@quasar/apollo" Quasar App Extension...
 App · Reading quasar.conf.js
 App · Extension(@quasar/apollo): Extending quasar.conf...
 App · Transpiling JS (Babel active)
 App · Extending SPA Webpack config
 App · Cleaned build artifact: "/app/dist/spa"
 App · Generating Webpack entry point
 App · Compiling with Webpack...
 App · Compiling SPA...

<--- Last few GCs --->

[28:0x5c933c0]    51865 ms: Scavenge (reduce) 477.7 (489.1) -> 477.1 (490.1) MB, 8.8 / 0.0 ms  (average mu = 0.590, current mu = 0.456) allocation failure
[28:0x5c933c0]    52059 ms: Scavenge (reduce) 478.8 (490.1) -> 478.3 (491.4) MB, 48.5 / 0.0 ms  (average mu = 0.590, current mu = 0.456) allocation failure
[28:0x5c933c0]    52246 ms: Scavenge (reduce) 479.8 (491.4) -> 479.4 (492.1) MB, 31.2 / 0.0 ms  (average mu = 0.590, current mu = 0.456) allocation failure


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa7ac10 node::Abort() [/usr/local/bin/node]
 2: 0x9a3c4d node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xc63f6e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xc642e7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xe2dd65  [/usr/local/bin/node]
 6: 0xe5d2f3 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/local/bin/node]
 7: 0xe69ea6 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/local/bin/node]
 8: 0xe55fcf v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/local/bin/node]
 9: 0xe56248 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/usr/local/bin/node]
10: 0xe48069 v8::internal::ItemParallelJob::Run() [/usr/local/bin/node]
11: 0xe6be30 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [/usr/local/bin/node]
12: 0xe6c673 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/usr/local/bin/node]
13: 0xe6ca35 v8::internal::MarkCompactCollector::Evacuate() [/usr/local/bin/node]
14: 0xe7f1a1 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/local/bin/node]
15: 0xe3b068 v8::internal::Heap::MarkCompact() [/usr/local/bin/node]
16: 0xe3c9f8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
17: 0xe3e985 v8::internal::Heap::HandleGCRequest() [/usr/local/bin/node]
18: 0xde18e7 v8::internal::StackGuard::HandleInterrupts() [/usr/local/bin/node]
19: 0x115c33a v8::internal::Runtime_StackGuardWithGap(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
20: 0x14f1df9  [/usr/local/bin/node]
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 134
ERROR: Service 'manager' failed to build : Build failed
```

**Comment by m0pam** [comment]
By the way, the issue is solved to me, my docker-compose runs smoothly now on Ubuntu 22, though I first must disable the systemd-resolv, otherwise the tcp p53 stays open and powerdns cannot bind to it (remember to modify /etc/resolv.conf afterwards in case you're using a vps).

**Comment by SakiiR** [comment]
> Hey @SakiiR
> 
> Sorry I sent the first message using the wrong account. Yes I did clone the actual master branch that includes the #21 merge.
> 
> During the build of `manager` I get the following JS stacktrace :
> 
> ```
> Step 7/18 : RUN yarn build
>  ---> Running in a5e757d61afa
> yarn run v1.22.5
> $ quasar build
> 
>  Build mode........ spa
>  Pkg quasar........ v1.15.19
>  Pkg @quasar/app... v2.2.8
>  Debugging......... no
>  Publishing........ no
> 
> Browserslist: caniuse-lite is outdated. Please run:
> npx browserslist@latest --update-db
> 
> Why you should do it regularly:
> https://github.com/browserslist/browserslist#browsers-data-updating
>  Configured browser support (at least 87.68% of global marketshare):
>  · Chrome for Android >= 90
>  · Firefox for Android >= 87
>  · Android >= 90
>  · Chrome >= 80
>  · Edge >= 87
>  · Firefox >= 79
>  · iOS >= 11.0-11.2
>  · Opera >= 71
>  · Safari >= 11.1
> 
>  App · Running "@quasar/apollo" Quasar App Extension...
>  App · Reading quasar.conf.js
>  App · Extension(@quasar/apollo): Extending quasar.conf...
>  App · Transpiling JS (Babel active)
>  App · Extending SPA Webpack config
>  App · Cleaned build artifact: "/app/dist/spa"
>  App · Generating Webpack entry point
>  App · Compiling with Webpack...
>  App · Compiling SPA...
> 
> <--- Last few GCs --->
> 
> [28:0x5c933c0]    51865 ms: Scavenge (reduce) 477.7 (489.1) -> 477.1 (490.1) MB, 8.8 / 0.0 ms  (average mu = 0.590, current mu = 0.456) allocation failure
> [28:0x5c933c0]    52059 ms: Scavenge (reduce) 478.8 (490.1) -> 478.3 (491.4) MB, 48.5 / 0.0 ms  (average mu = 0.590, current mu = 0.456) allocation failure
> [28:0x5c933c0]    52246 ms: Scavenge (reduce) 479.8 (491.4) -> 479.4 (492.1) MB, 31.2 / 0.0 ms  (average mu = 0.590, current mu = 0.456) allocation failure
> 
> 
> <--- JS stacktrace --->
> 
> FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
>  1: 0xa7ac10 node::Abort() [/usr/local/bin/node]
>  2: 0x9a3c4d node::FatalError(char const*, char const*) [/usr/local/bin/node]
>  3: 0xc63f6e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
>  4: 0xc642e7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
>  5: 0xe2dd65  [/usr/local/bin/node]
>  6: 0xe5d2f3 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/local/bin/node]
>  7: 0xe69ea6 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/local/bin/node]
>  8: 0xe55fcf v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/local/bin/node]
>  9: 0xe56248 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/usr/local/bin/node]
> 10: 0xe48069 v8::internal::ItemParallelJob::Run() [/usr/local/bin/node]
> 11: 0xe6be30 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [/usr/local/bin/node]
> 12: 0xe6c673 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/usr/local/bin/node]
> 13: 0xe6ca35 v8::internal::MarkCompactCollector::Evacuate() [/usr/local/bin/node]
> 14: 0xe7f1a1 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/local/bin/node]
> 15: 0xe3b068 v8::internal::Heap::MarkCompact() [/usr/local/bin/node]
> 16: 0xe3c9f8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
> 17: 0xe3e985 v8::internal::Heap::HandleGCRequest() [/usr/local/bin/node]
> 18: 0xde18e7 v8::internal::StackGuard::HandleInterrupts() [/usr/local/bin/node]
> 19: 0x115c33a v8::internal::Runtime_StackGuardWithGap(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
> 20: 0x14f1df9  [/usr/local/bin/node]
> Aborted (core dumped)
> error Command failed with exit code 134.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> The command '/bin/sh -c yarn build' returned a non-zero code: 134
> ERROR: Service 'manager' failed to build : Build failed
> ```

Hey,

It looks like you don't have enough RAM on the machine you are building pwn-machine on. Can you try on a different machine with more memory just to be sure this is the problem ?

**Comment by BZHuntShampu** [comment]
> Hey,
> 
> It looks like you don't have enough RAM on the machine you are building pwn-machine on. Can you try on a different machine with more memory just to be sure this is the problem ?

You are right, I ran the build while some heavy process was running in the background.
The build process seems to be working now (still compiling but no crash so far).

Thank you for you help

**Comment by m0pam** [comment]
@SakiiR I think we can close the issue now, thanks for the support :+1:

**Comment by SakiiR** [comment]
Yes we can =)

Feel free to open a new one if you encounter any other issue.
